import lightOrange from '../assets/buttons/lightOrange.png'
import orange from '../assets/buttons/orange.png'
import wine from '../assets/buttons/wine.png'

export const theme: any = {
  space: [0, 4, 8, 16, 32, 64, 128, 256, 512],
  fonts: {
    body: 'Nunito',
    heading: 'inherit',
    monospace: 'Menlo, monospace',
  },
  fontSizes: [12, 14, 16, 18, 20, 24, 30, 48, 64, 96],
  fontWeights: {
    body: 500,
    bold: 700,
    heading: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.125,
  },
  colors: {
    darkGreen: '#3D7265',
    downGradedOrange: '#FFC875',
    gray: '#474044',
    green: '#3EBA9B',
    lightGray: '#F5F5F5',
    lightOrange: '#F5E4AC',
    orange: '#FEAD34',
    red: '#DA3C3D',
    softGreen: '#79B8A8',
    softOrange: '#FFD89E',
    softRed: '#D56364',
    wine: '#1E0413',
  },
  sizes: {
    container: '100%',
  },
  styles: {
    tr: {
      'nth-child(even)': { backgroundColor: 'red' },
    },
    root: {
      backgroundColor: 'white',
      fontWeight: 'body',
      fontFamily: 'body',
      lineHeight: 'body',
    },
    navlink: {
      color: 'gray',
      fontFamily: 'heading',
      fontSize: 3,
      fontWeight: 700,
      marginLeft: '35px',
      my: '8px',
      textDecoration: 'none',
      '&: hover': {
        color: 'red',
      },
    },
    manageLink: {
      color: 'white',
      fontFamily: 'heading',
      fontSize: 3,
      fontWeight: 700,
      marginLeft: '35px',
      my: '8px',
      textDecoration: 'none',
      '&: hover': {
        color: 'gray',
      },
    },
    error: {
      color: 'red',
      fontSize: 2,
      textDecoration: 'none',
    },
    info: {
      color: 'green',
      fontSize: 2,
      textDecoration: 'none',
    },
    warning: {
      color: 'orange',
      fontSize: 2,
      textDecoration: 'none',
    },
  },
  buttons: {
    primary: {
      backgroundImage: `url(${lightOrange})`,
      backgroundPosition: '0 -100%',
      backgroundRepeat: 'repeat-x',
      bg: '#F5F5F5',
      borderRadius: '10px',
      color: 'gray',
      cursor: 'pointer',
      height: '50px',
      outline: 'none',
      transition: '1s ease',
      userSelect: 'none',
      whiteSpace: 'nowrap',
      width: '150px',
      '&:hover': {
        backgroundPosition: '500% 100%',
        fontSize: 3,
      },
    },
    red: {
      backgroundImage: `url(${wine})`,
      backgroundPosition: '0 -100%',
      backgroundRepeat: 'repeat-x',
      bg: 'red',
      borderRadius: '10px',
      color: '#fff',
      cursor: 'pointer',
      height: '50px',
      outline: 'none',
      transition: '1s ease',
      userSelect: 'none',
      width: '150px',
      whiteSpace: 'nowrap',
      '&:hover': {
        backgroundPosition: '500% 100%',
        fontSize: 3,
      },
    },
    green: {
      backgroundImage: `url(${orange})`,
      backgroundPosition: '0 -100%',
      backgroundRepeat: 'repeat-x',
      bg: 'green',
      borderRadius: '10px',
      color: '#fff',
      cursor: 'pointer',
      height: '50px',
      outline: 'none',
      transition: '1s ease',
      userSelect: 'none',
      width: '150px',
      whiteSpace: 'nowrap',
      '&:hover': {
        backgroundPosition: '500% 100%',
        fontSize: 3,
      },
    },
    orangeRed: {
      backgroundImage: `url(${orange})`,
      backgroundPosition: '0 -100%',
      backgroundRepeat: 'repeat-x',
      bg: 'red',
      borderRadius: '10px',
      color: '#fff',
      cursor: 'pointer',
      height: '50px',
      outline: 'none',
      transition: '1s ease',
      userSelect: 'none',
      width: '150px',
      whiteSpace: 'nowrap',
      '&:hover': {
        backgroundPosition: '500% 100%',
        fontSize: 3,
      },
    },
    gray: {
      backgroundImage: `url(${orange})`,
      backgroundPosition: '0 -100%',
      backgroundRepeat: 'repeat-x',
      bg: '#7A7A7A',
      borderRadius: '10px',
      color: '#fff',
      cursor: 'pointer',
      height: '50px',
      outline: 'none',
      transition: '1s ease',
      userSelect: 'none',
      width: '150px',
      whiteSpace: 'nowrap',
      '&:hover': {
        backgroundPosition: '500% 100%',
        fontSize: 3,
      },
    },
    sizeLink: {
      backgroundColor: 'transparent',
      border: 'none',
      color: 'darkGreen',
      cursor: 'pointer',
      fontSize: 6,
      outline: 'none',
      transition: '0.2s ease',
      '&: focus': {
        color: 'orange',
        transform: 'scale(1.3)',
      },
      '&: hover': {
        color: 'orange',
        transform: 'scale(1.3)',
      },
    },
  },
  cards: {
    primary: {
      bg: '#F9F9F9',
      borderRadius: 4,
      boxShadow: '0 0 8px rgba(0, 0, 0, 0.08)',
      transition: '0.6s ease',
      width: '310px',
      '&: hover': {
        transform: 'scale(1.05)',
      },
      '@media screen and (max-width: 1700px)': {
        width: '300px',
      },
      '@media screen and (max-width: 840px)': {
        width: '350px',
      },
      '@media screen and (max-width: 640px)': {
        width: '280px',
      },
      '@media screen and (max-width: 480px)': {
        width: '350px',
      },
      '@media screen and (max-width: 440px)': {
        width: '240px',
      },
    },
    manage: {
      bg: '#F9F9F9',
      borderRadius: '20px',
      boxShadow: '0 0 8px rgba(0, 0, 0, 0.08)',
      transition: '0.6s ease',
      width: '550px',
      '&: hover': {
        transform: 'scale(1.05)',
      },
      '@media screen and (max-width: 1700px)': {
        width: '400px',
      },
      '@media screen and (max-width: 840px)': {
        width: '380px',
      },
      '@media screen and (max-width: 640px)': {
        width: '310px',
      },
      '@media screen and (max-width: 480px)': {
        width: '300px',
      },
      '@media screen and (max-width: 440px)': {
        width: '300px',
      },
    },
  },
  text: {
    default: {
      color: 'gray',
      fontSize: 2,
    },
    title: {
      color: `red`,
      fontSize: 6,
      fontWeight: 'bold',
      textDecoration: 'none',
    },
    title_2: {
      color: `red`,
      fontSize: 5,
      fontWeight: 600,
      textDecoration: 'none',
    },
    title_3: {
      color: `red`,
      fontSize: 4,
      fontWeight: 500,
      textDecoration: 'none',
    },
    title_4: {
      color: `gray`,
      fontSize: 30,
      fontWeight: 'bold',
      textDecoration: 'none',
    },
    summary: {
      color: 'gray',
      fontSize: 3,
    },
    summary_2: {
      color: 'gray',
      fontSize: 2,
    },
    summary_3: {
      color: 'gray',
      fontSize: 1,
    },
  },
  images: {
    card: {
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      width: '100%',
      height: '180px',
    },
    fullwidth: {
      height: '70vh',
      objectFit: 'cover',
      width: '100%',
    },
    profile: {
      borderRadius: '20px',
      height: '20vh',
      left: '20%',
      objectFit: 'cover',
      position: 'absolute',
      top: '100px',
      width: '20vh',
      '@media screen and (max-width:425px)': {
        height: '20vh',
        left: '30%',
      },
      '@media screen and (min-width:426px) and (max-width:768px)': {
        height: '25vh',
        left: '8%',
      },
      '@media screen and (min-width:769px) and (max-width:1024px)': {
        height: '20vh',
        left: '7%',
        top: '18%',
      },
    },
    medium: {
      height: '40vh',
      objectFit: 'cover',
      width: '100%',
    },
    fragment: {
      height: '30vh',
      objectFit: 'cover',
      width: '100%',
    },
    logo: {
      objectFit: 'cover',
      width: '100%',
    },
  },
  forms: {
    label: {
      color: 'gray',
      fontSize: 2,
      fontWeight: 500,
      marginTop: 10,
      outline: 'none',
    },
    input: {
      border: '0px solid black',
      borderBottom: '1px solid gray',
      borderColor: 'gray',
      borderRadius: 0,
      color: 'gray',
      outline: 'none',
    },
    textarea: {
      border: '1px solid gray',
      borderRadius: '15px',
      color: 'gray',
      fontFamily: 'Nunito',
      fontSize: '20px',
      margin: 10,
      maxWidth: '95%',
      outline: 'none',
      padding: '10px',
      resize: 'none',
    },
    radio: {
      color: 'gray',
      '&: hover': {
        transform: 'scale(1.2)',
      },
    },
    checkbox: {
      color: 'gray',
      '&: hover': {
        transform: 'scale(1.2)',
      },
    },
  },
  layout: {
    container: {
      backgroundColor: 'transparent',
      border: '0px solid ',
      borderRadius: '10px',
      margin: '10px',
      padding: '15px',
    },
    noMargin: {
      backgroundColor: 'transparent',
      border: 'none',
      borderRadius: '0',
      margin: '0',
      padding: '0',
    },
  },
  chips: {
    content: {
      alignItems: 'center',
      borderRadius: '10px',
      display: 'flex',
      fontSize: 2,
      height: 'fit-content',
      justifyContent: 'center',
      listStyle: 'none',
      margin: '2px 4px 2px 4px',
      minHeight: '30px',
      padding: '0 8px',
      width: 'fit-content',
    },
    removeButton: {
      alignItems: 'center',
      appearance: 'none',
      backgroundColor: '#ccc',
      border: 'none',
      borderRadius: '50%',
      color: 'white',
      cursor: 'pointer',
      display: 'inline-flex',
      fontSize: '12px',
      height: '16px',
      justifyContent: 'center',
      marginLeft: '8px',
      minHeight: '16px',
      minWidth: '16px',
      transform: 'rotate(45deg)',
      width: '16px',
      '&: hover': {
        backgroundColor: 'gray',
      },
    },
  },
  toggleSwitches: {
    content: {
      display: 'inline-block',
      height: '30px',
      position: 'relative',
      width: '50px',
    },
    input: {
      height: 0,
      opacity: 0,
      width: 0,
    },
    slider: {
      backgroundColor: '#ccc',
      borderRadius: '30px',
      bottom: 0,
      cursor: 'pointer',
      left: 0,
      position: 'absolute',
      right: 0,
      top: 0,
      transition: '0.4s',
      '&: before': {
        backgroundColor: 'white',
        borderRadius: '50%',
        bottom: '2px',
        content: '""',
        height: '26px',
        left: '2px',
        position: 'absolute',
        transition: '0.4s',
        width: '26px',
      },
    },
  },
  search: {
    item: {
      backgroundColor: 'white',
      border: 'none',
      borderRadius: '5px',
      color: '#474747',
      display: 'inline-flex',
      height: '32px',
      my: '8px',
      px: '16px',
      py: '8px',
      '&:hover': {
        color: 'black',
        outLine: 'none',
      },
      '&:focus': {
        color: 'black',
        outline: 'none',
      },
    },
    bar: {
      width: '100%',
      display: 'inline-flex',
      gap: '5px',
    },
  },
}
